version: 0.2

phases:
  install:
    commands:
      - echo "Installing required tools..."
      - curl -LO "https://k8s.io"
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin/kubectl
      - curl --silent --location "https://github.com" | tar xz -C /tmp
      - mv /tmp/eksctl /usr/local/bin
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - echo Setting up Kubeconfig...
      - aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t brain-tasks-app .
      - docker tag brain-tasks-app:latest $REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker tag brain-tasks-app:latest $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to ECR...
      - docker push $REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker push $REPOSITORY_URI:latest
      - echo Updating Kubernetes manifests...
      - sed -i "s|brain-tasks-app:latest|brain-tasks-app:$CODEBUILD_RESOLVED_SOURCE_VERSION|g" kubernetes/deployment.yml
      - echo Deploying to AWS EKS cluster...
      - kubectl apply -f kubernetes/deployment.yml
      - kubectl apply -f kubernetes/service.yml

