apiVersion: v1
kind: Service
metadata:
  name: brain-tasks-service
spec:
  type: LoadBalancer
  selector:
    app: brain-tasks-app
  ports:
    - protocol: TCP
      port: 80         # The port you open in your browser
      targetPort: 80   # CHANGE THIS TO 80 (where Nginx is listening)
